### ISSUE TITLE
KB3266 partial functionality

### ISSUE THREAD

**Issue by f22raptorroland** [araczkowski/BK3266#3]
I have a board just as **araczkowski** has on the pictures. 
Mine has the usb/SD card unpopulated on the board. 

When I tied on baud 9600, only a few commands worked.
+SNAME+, REBOOT.
All other commands return : ERR\n

Also, I have to end commands with "**\n**" instead "**\r\n**".  "COM+SNAME+XXXX\n"

Do you have any idea what can be the problem? 

I'd want to query the phone volume and turn a motorized potentiometer on an amplifier accordingly.

**Comment by araczkowski** [comment]
9600 is ok
I stopped to use this one, but I can see in my old code that I used stty to communicate with this board (I did this from Android console)

I was able to send any command like this:

- set aux mode 
```
stty -F /dev/ttyS0 9600 && echo COM+MAX\r\n > /dev/ttyS0
```

- set sound mode (equalizer)
```
stty -F /dev/ttyS0 9600 && echo COM+SETEQBOOST\r\n > /dev/ttyS0
```
- set bloototh mode
```
stty -F /dev/ttyS0 9600 && echo COM+MBT\r\n > /dev/ttyS0
```
- disable tone
```
stty -F /dev/ttyS0 9600 && echo COM+TONEOFF\r\n > /dev/ttyS0
```
etc

good luck

**Comment by f22raptorroland** [comment]
Thank you for the fast reply. 

I've been toying around in the last few days, but of no avail.

Can you please tell me **where did you find these commands?** 
Maybe I am missing something.

Tough, I can communicate with the board, I just all the other functions

My board is a bit different, but the Bk3266 board seems to be the same. **Do you think it has a different firmware on it?** 
One that is missing the other commands, or do they come pre-programmed.

[Differences of boards:](https://photos.app.goo.gl/fBgqkQgN3go7a8Jj8)
Few components missing/different arrangement, tht holers behind USB, and I have an extra tht hole (V) next to (RX,TX,GND) I applied 3.3V

Also, I see on the picture you have the 3.3 jack connected. 
When I connect that. I can't send commands, or connect to it **is it some kind of transmitting mode?**

**Comment by araczkowski** [comment]
im not using this anymore, I'm not able to give you good answers.. sorry
maybe try here https://github.com/tomaskovacik/BK3254

**Comment by f22raptorroland** [comment]
Thank you. 
I just found the git you linked yesterday. 

It is very helpful. It seems my board is a different version, and lacks this functionality.
The irony is that the older ones have all the commands.

If you are not using it anymore, can you please recommend something for a similar application? 
What are you using nowadays? 

I'd like to query Bluetooth volume (AVRCP). That's all the functions I really need.
